<a href="https://colab.research.google.com/github/alishabohara03/Machine-Learning/blob/main/IntoductionML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Introduction to Numpy
What will we cover?

Creating arrays

Multi dimensional array Rnadomly generated arrays Element wise operators

In [1]:
import numpy as np

Creating Arrays


In [2]:
 var = np.zeros(5)
 print(type(var))

<class 'numpy.ndarray'>


In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
var = np.array([1, 2, 3, 4])
var[2] = 6
print(var)

[1 2 6 4]


In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

create arrays with evenly spaced numbers within a specified range

In [9]:
np.linspace(0, 100, 10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

Multidimensional Arrays

In [10]:
# creating an MD unit Array of size (5,2)
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
#Generate a random array of size (3, 5) with elements of your choice

# zero_array = np.zeros((5, 2))
# random_array = np.random.randint(1, 11, (3, 5))


# print("\nRandom Array (3,5):")
# print(random_array)

n= np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [6, 7, 8, 9, 0]
])
n

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [6, 7, 8, 9, 0]])

In [12]:
#update this element of an array with index

# random_array = np.random.randint(1, 11, (3, 5))

# print("Original Array:")
# print(random_array)
# random_array[1, 2] = 99

# print("\nUpdated Array:")
# print(random_array)


n[:, 2] = [2, 4, 5]
n

array([[1, 2, 2, 4, 5],
       [2, 3, 4, 5, 6],
       [6, 7, 5, 9, 0]])

Randomly generated arrays
-Numpy can create arrays filled with random numbers.

To ensure the reproducibility, you can set a seed using np.random.seed()

Everytime you run the code with np.random.seed(2),it will generate the exact same random numbers.

if you remove or change the seed valuses, the sequence of random numbers will be changed.

In [13]:
np.random.rand(3)

array([0.5943214 , 0.11041489, 0.8128376 ])

In [14]:
np.random.seed(2)
np.random.rand(5)

array([0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ])

In [15]:
np. random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [16]:
np.random.randn(5, 2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [17]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

E;ementwise operations

In [18]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [20]:
#comparision operation
#you can  perform element - wise comparisons and create boolean arrays
a

array([0, 1, 2, 3, 4])

In [21]:
a >= 2

array([False, False,  True,  True,  True])

In [22]:
a > b

array([False, False, False, False, False])

In [23]:
#Summarizing
#Numpy provides functions for summarizing array of data
a

array([0, 1, 2, 3, 4])

In [24]:
#standard devistion
a. std()

1.4142135623730951

In [25]:
#minimum value of an array
a.min()

0

In [26]:
#max value of an array
a.max()

4

In [27]:
#sum of  elements of an array
a.sum()

10